import { createRequire } from "node:module";
const runtimeRequire = createRequire(__filename);
import assert = require("node:assert/strict");
import { readFileSync } from "node:fs";

async function main() {
  const packageVersion = runtimeRequire("../package.json").version;
  const esm = await import("large-image-ingest");
  const esmCore = await import("large-image-ingest/core");
  const esmBrowser = await import("large-image-ingest/browser");
  const esmConformance = await import("large-image-ingest/conformance");
  const esmProvenance = await import("large-image-ingest/provenance");
  const esmPreservation = await import("large-image-ingest/preservation");
  const esmProfiles = await import("large-image-ingest/profiles");
  const esmWorkflow = await import("large-image-ingest/workflow");
  const esmTus = await import("large-image-ingest/transport-tus");
  const esmS3 = await import("large-image-ingest/transport-s3");
  const esmNode = await import("large-image-ingest/node");
  const esmReact = await import("large-image-ingest/react");
  const esmReactUi = await import("large-image-ingest/react-ui");
  const esmTiff = await import("large-image-ingest/tiff");
  const cjs = runtimeRequire("large-image-ingest");
  const cjsCore = runtimeRequire("large-image-ingest/core");
  const cjsConformance = runtimeRequire("large-image-ingest/conformance");
  const cjsProvenance = runtimeRequire("large-image-ingest/provenance");
  const cjsPreservation = runtimeRequire("large-image-ingest/preservation");
  const cjsProfiles = runtimeRequire("large-image-ingest/profiles");
  const cjsWorkflow = runtimeRequire("large-image-ingest/workflow");
  const cjsTus = runtimeRequire("large-image-ingest/transport-tus");
  const cjsS3 = runtimeRequire("large-image-ingest/transport-s3");
  const cjsNode = runtimeRequire("large-image-ingest/node");
  const cjsReact = runtimeRequire("large-image-ingest/react");
  const cjsReactUi = runtimeRequire("large-image-ingest/react-ui");
  const cjsTiff = runtimeRequire("large-image-ingest/tiff");
  const reactUiStyles = runtimeRequire.resolve("large-image-ingest/react-ui/styles.css");

  assert.equal(typeof esm.planChunks, "function");
  assert.equal(typeof esm.createIngestSession, "function");
  assert.equal(typeof esm.parseResumeRecord, "function");
  assert.equal(typeof esm.createSafeEventSummary, "function");
  assert.equal(typeof esm.createDerivativeReference, "function");
  assert.equal(typeof esm.attachDerivative, "function");
  assert.equal(typeof esm.createPreviewDerivative, "function");
  assert.equal(typeof esmCore.createIngestSession, "function");
  assert.equal(typeof esmBrowser.createBrowserWorkerChecksumExecutor, "function");
  assert.equal(typeof esmConformance.runTransportConformance, "function");
  assert.equal(esmConformance.TRANSPORT_CONFORMANCE_CATALOG.scenarios.length, 10);
  assert.equal(typeof esmProvenance.createIngestProvenanceRecorder, "function");
  assert.equal(esmProvenance.INGEST_PROVENANCE_SCHEMA_VERSION, "large-image-ingest.provenance.v1");
  assert.equal(typeof esmPreservation.evaluatePreservationMapping, "function");
  assert.equal(typeof esmPreservation.exportBagIt, "function");
  assert.equal(typeof esmPreservation.exportOcflObject, "function");
  assert.equal(typeof esmProfiles.loadBundledDomainProfile, "function");
  assert.equal(typeof esmProfiles.evaluateDomainValidationProfile, "function");
  assert.equal(typeof esmWorkflow.createVerifiedIngestWorkflow, "function");
  assert.equal(esmWorkflow.INGEST_EVIDENCE_BUNDLE_SCHEMA_VERSION, "large-image-ingest.evidence-bundle.v1");
  assert.equal(typeof esmCore.validateResumeRecord, "function");
  assert.equal(typeof esmCore.redactUploadSessionSnapshot, "function");
  assert.equal(typeof esmCore.validateManifestDerivatives, "function");
  assert.equal(typeof esmTus.createTusTransport, "function");
  assert.equal(typeof esmS3.createS3MultipartTransport, "function");
  assert.equal(typeof esmNode.createNasGateway, "function");
  assert.equal(typeof esmNode.calculateNodeFileChecksum, "function");
  assert.equal(typeof esmNode.createNodeStoredFileVerifier, "function");
  assert.equal(typeof esmNode.createFilesystemPreservationHandoff, "function");
  assert.equal(typeof esmNode.createMetadataDerivative, "function");
  assert.equal(typeof esmNode.createTilePyramidDerivative, "function");
  assert.equal(typeof esmReact.createIngestController, "function");
  assert.equal(typeof esmReact.createVerifiedIngestController, "function");
  assert.equal(typeof esmReact.VerifiedIngestProvider, "function");
  assert.equal(typeof esmReact.IngestProvider, "function");
  assert.equal(typeof esmReact.useIngestSession, "function");
  assert.equal(typeof esmReactUi.InspectionUploadPanel, "function");
  assert.equal(typeof esmReactUi.VerifiedIngestPanel, "function");
  assert.equal(typeof esmReactUi.InspectionUploadProvider, "function");
  assert.equal(typeof esmReactUi.useInspectionUploadUi, "function");
  assert.equal(typeof esmTiff.probeTiffMetadata, "function");
  assert.equal(typeof esmTiff.toTiffImageMetadata, "function");
  assert.equal(typeof cjs.planChunks, "function");
  assert.equal(typeof cjs.createIngestSession, "function");
  assert.equal(typeof cjs.parseResumeRecord, "function");
  assert.equal(typeof cjs.createSafeEventSummary, "function");
  assert.equal(typeof cjs.createDerivativeReference, "function");
  assert.equal(typeof cjs.attachDerivative, "function");
  assert.equal(typeof cjs.createPreviewDerivative, "function");
  assert.equal(typeof cjsCore.createIngestSession, "function");
  assert.equal(typeof cjsConformance.runTransportConformance, "function");
  assert.equal(cjsConformance.TRANSPORT_CONFORMANCE_CATALOG.scenarios.length, 10);
  assert.equal(typeof cjsProvenance.createIngestProvenanceRecorder, "function");
  assert.equal(cjsProvenance.INGEST_PROVENANCE_SCHEMA_VERSION, "large-image-ingest.provenance.v1");
  assert.equal(typeof cjsPreservation.evaluatePreservationMapping, "function");
  assert.equal(typeof cjsPreservation.validateBagIt, "function");
  assert.equal(typeof cjsPreservation.validateOcflObject, "function");
  assert.equal(typeof cjsProfiles.loadBundledDomainProfile, "function");
  assert.equal(typeof cjsProfiles.deriveDomainValidationProfile, "function");
  assert.equal(typeof cjsWorkflow.createVerifiedIngestWorkflow, "function");
  assert.equal(cjsWorkflow.WORKFLOW_CHECKPOINT_SCHEMA_VERSION, "large-image-ingest.workflow-checkpoint.v1");
  assert.equal(cjsCore.normalizeTransportRecoveryCapabilities(undefined).persistentResume, false);
  assert.equal(typeof cjsCore.validateResumeRecord, "function");
  assert.equal(typeof cjsCore.redactUploadSessionSnapshot, "function");
  assert.equal(typeof cjsCore.validateManifestDerivatives, "function");
  assert.equal(typeof cjsTus.createTusTransport, "function");
  assert.equal(typeof cjsS3.createS3MultipartTransport, "function");
  assert.equal(typeof cjsNode.createNasGateway, "function");
  assert.equal(typeof cjsNode.calculateNodeFileChecksum, "function");
  assert.equal(typeof cjsNode.createNodeStoredFileVerifier, "function");
  assert.equal(typeof cjsNode.createFilesystemPreservationHandoff, "function");
  assert.equal(typeof cjsNode.createMetadataDerivative, "function");
  assert.equal(typeof cjsNode.createTilePyramidDerivative, "function");
  assert.equal(typeof cjsReact.createIngestController, "function");
  assert.equal(typeof cjsReact.createVerifiedIngestController, "function");
  assert.equal(typeof cjsReact.VerifiedIngestProvider, "function");
  assert.equal(typeof cjsReact.IngestProvider, "function");
  assert.equal(typeof cjsReact.useIngestSession, "function");
  assert.equal(typeof cjsReactUi.InspectionUploadPanel, "function");
  assert.equal(typeof cjsReactUi.VerifiedIngestPanel, "function");
  assert.equal(typeof cjsReactUi.InspectionUploadProvider, "function");
  assert.equal(typeof cjsReactUi.useInspectionUploadUi, "function");
  assert.equal(typeof cjsTiff.probeTiffMetadata, "function");
  assert.equal(typeof cjsTiff.toTiffImageMetadata, "function");
  assert.match(reactUiStyles, /styles[\\/]react-ui\.css$/);
  const workflowSource = readFileSync(runtimeRequire.resolve("large-image-ingest/workflow"), "utf8");
  assert.doesNotMatch(workflowSource, /node:|node-workflow|preservation\.js|react/i);
  assert.deepEqual(esm.planChunks(10, { chunkSize: 256 * 1024 }).chunks, [
    { index: 0, start: 0, end: 10, size: 10 }
  ]);
  assert.deepEqual(cjs.planChunks(10, { chunkSize: 256 * 1024 }).chunks, [
    { index: 0, start: 0, end: 10, size: 10 }
  ]);
  const source = Object.assign(new Blob(["producer-version"]), { name: "producer-version.bin" });
  Object.defineProperty(source, "name", { value: "producer-version.bin" });
  const esmManifest = await esm.createManifest(source, { checksum: false });
  const cjsManifest = await cjs.createManifest(source, { checksum: false });
  assert.equal(esmManifest.library.version, packageVersion);
  assert.equal(cjsManifest.library.version, packageVersion);
  assert.equal(esmManifest.schemaVersion, "large-image-ingest.manifest.v1");
  assert.equal(cjsManifest.schemaVersion, "large-image-ingest.manifest.v1");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
